# Generated by Django 3.2.4 on 2021-07-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimages',
            name='height',
            field=models.IntegerField(default=550),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='galleryimages',
            name='width',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='galleryimages',
            name='image',
            field=models.ImageField(height_field='height', upload_to='', width_field='width'),
        ),
    ]
