# Generated by Django 3.2.4 on 2021-07-07 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20210707_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimages',
            name='height',
        ),
        migrations.RemoveField(
            model_name='galleryimages',
            name='width',
        ),
    ]
