# Generated by Django 3.2.4 on 2021-07-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0003_auto_20210707_2028"),
    ]

    operations = [
        migrations.AddField(
            model_name="galleryimages",
            name="height",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="galleryimages",
            name="width",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
