# Generated by Django 3.2.4 on 2021-07-13 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20210707_2043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimages',
            options={'verbose_name_plural': 'Gallery images'},
        ),
    ]
