# Generated by Django 3.2.4 on 2021-07-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0003_rename_original_bag_order_original_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderlineitem",
            name="product_type",
            field=models.CharField(max_length=32),
        ),
    ]
