# Generated by Django 3.2.4 on 2021-07-13 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0002_auto_20210713_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customworktype',
            old_name='name',
            new_name='work_type',
        ),
    ]
