# Generated by Django 3.2.4 on 2021-07-13 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("custom", "0003_rename_name_customworktype_work_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customsizes",
            options={"verbose_name_plural": "Custom sizes"},
        ),
    ]
