# Generated by Django 3.2.4 on 2021-07-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom", "0004_alter_customsizes_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomersFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_file",
                    models.FileField(
                        blank=True, null=True, upload_to="custom/customers_files"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Customers Files",
            },
        ),
    ]
