# Generated by Django 3.2.4 on 2021-07-22 15:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0006_customersfiles_customer_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersfiles',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customersfiles',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
